id: 99231cd268024265ba6d1d3fc274c10f
initial_creation_type: ocr
source_metadata:
  volumes:
    dbb4d5e5cc60468ca0f4608d448c615a:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
